### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Minix-Issue** [DeathsGun/Issues#3]
---- Minecraft Crash Report ----
<--- Minix Infos --->Minix v1.0Modded: No variable wasn't changed// You should try our sister game, Minceraft!

Time: 15.09.16 22:20
Description: Test

java.lang.Exception: Test
	at de.deathsgun.minix.Minix.<init>(Minix.java:72)
	at net.minecraft.server.MinecraftServer.Start(MinecraftServer.java:906)
	at main.Main.main(Main.java:19)
Pls send this Crash Report to me at BitBucket!(https://bitbucket.org/DeathsGun/Minix)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Mac OS X (x86_64) version 10.12
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 126106824 bytes (120 MB) / 163053568 bytes (155 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

**Comment by Minix-Issue** [comment]
@DeathsGun we have a new Issue byServer

**Comment by DeathsGun** [comment]
This was a test my new Minix server version with integrated issue handler
